<?php
require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use Illuminate\Support\Facades\DB;

config(['database.connections.legacy_restore' => [
    'driver' => 'mysql',
    'host' => env('DB_HOST', '127.0.0.1'),
    'port' => env('DB_PORT', '3306'),
    'database' => 'findmyinterior_legacy_restore',
    'username' => env('DB_USERNAME', 'root'),
    'password' => env('DB_PASSWORD', ''),
]]);

$conn = DB::connection('legacy_restore');

$wallets = $conn->table('wallets')->get();
$users = $conn->table('users')->get()->keyBy('id');
$transactions = $conn->table('wallet_transactions')->get();

$ledger_by_wallet = [];
foreach ($transactions as $tx) {
    if (!isset($ledger_by_wallet[$tx->wallet_id])) {
        $ledger_by_wallet[$tx->wallet_id] = ['cr' => 0, 'dr' => 0];
    }
    if ($tx->type === 'credit') $ledger_by_wallet[$tx->wallet_id]['cr'] += $tx->amount;
    if ($tx->type === 'debit') $ledger_by_wallet[$tx->wallet_id]['dr'] += $tx->amount;
}

$mismatch_count = 0;
$mock_mismatch_count = 0;
$real_mismatch_count = 0;
$mock_but_no_wallet = 0;

foreach ($wallets as $w) {
    $uid = $w->user_id;
    $ledger = $ledger_by_wallet[$w->id] ?? ['cr' => 0, 'dr' => 0];
    $net = $ledger['cr'] - $ledger['dr'];
    
    if (abs($w->balance - $net) > 0.01) {
        $mismatch_count++;
        
        $user = $users[$uid] ?? null;
        if ($user) {
            if ($user->is_mock) {
                $mock_mismatch_count++;
            } else {
                $real_mismatch_count++;
            }
        } else {
            // User deleted?
            $real_mismatch_count++;
        }
    }
}

$total_mocks = $conn->table('users')->where('is_mock', 1)->count();
$total_real = $conn->table('users')->where('is_mock', 0)->count();

$report = [
    'analysis' => [
        'total_mismatches' => $mismatch_count,
        'mock_mismatches' => $mock_mismatch_count,
        'real_mismatches' => $real_mismatch_count,
    ],
    'user_population' => [
        'total_mock_users' => $total_mocks,
        'total_real_users' => $total_real
    ],
    'seeder_evidence' => "Found DB::table('wallets')->insert(['user_id' => \$user->id, 'balance' => rand(0, 200)]); in database/seeders/MockUserSeeder.php and others."
];

file_put_contents('C:\Users\Aryan\.gemini\antigravity-ide\brain\43711a4e-6310-44ce-a019-6e6633ee92d0\wallet_origin_verification.json', json_encode($report, JSON_PRETTY_PRINT));

$md = "# Wallet Origin & Spendability Verification\n\n";
$md .= "## Population Truth\n";
$md .= "- **Total Mismatches**: {$mismatch_count}\n";
$md .= "- **Mock Mismatches**: {$mock_mismatch_count} (These were generated by Faker/Seeder)\n";
$md .= "- **Real User Mismatches**: {$real_mismatch_count}\n\n";

$md .= "## Global User Context\n";
$md .= "- **Total Mock Users in DB**: {$total_mocks}\n";
$md .= "- **Total Real Users in DB**: {$total_real}\n\n";

$md .= "## Source Code Evidence\n";
$md .= "The exact line responsible for creating the arbitrary balances (88, 198, 104, etc.) without transaction history was found in `MockUserSeeder.php`:\n";
$md .= "```php\nDB::table('wallets')->insert(['user_id' => \$user->id, 'balance' => rand(0, 200)]);\n```\n";
$md .= "And similar logic for suppliers (`rand(0, 1000)`) and builders (`rand(500, 5000)`).\n\n";

$md .= "## Conclusion on Spendability\n";
if ($real_mismatch_count === 0 && $mock_mismatch_count === $mismatch_count) {
    $md .= "The ENTIRE mismatch population consists of **MOCK USERS** created by a seeder script. These balances do NOT represent real purchasing power or real financial liabilities. They are synthetic test data artifacts.\n";
} else {
    $md .= "While {$mock_mismatch_count} are mock, there are still {$real_mismatch_count} real users with mismatched balances. Further investigation is needed for the real users.\n";
}

file_put_contents('C:\Users\Aryan\.gemini\antigravity-ide\brain\43711a4e-6310-44ce-a019-6e6633ee92d0\wallet_origin_verification.md', $md);
echo "Verification complete. Mock mismatches: $mock_mismatch_count, Real: $real_mismatch_count\n";
